version: '3'

services:
  web:
    build:
      context: .
      args:
        ENV: ${ENV:-development}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=${DEBUG:-True}
    command: ${COMMAND:-python manage.py runserver 0.0.0.0:8000}